[build]
  command = "npm run build"
  publish = "client/build"
  functions = "server/functions"

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  REACT_APP_API_BASE_URL = "/api"

[context.deploy-preview.environment]
  REACT_APP_API_BASE_URL = "/api"

[context.branch-deploy.environment]
  REACT_APP_API_BASE_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
